// flow-typed signature: 037e6f97efdc670f407f0acd6746e8c0
// flow-typed version: <<STUB>>/form-data_vv2.x.x/flow_v0.79.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'form-data'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'form-data' {
  declare module.exports: () => FormData
}

declare class FormData {
  append: (string, string) => void,
}
/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'form-data/lib/browser' {
  declare module.exports: any;
}

declare module 'form-data/lib/form_data' {
  declare module.exports: any;
}

declare module 'form-data/lib/populate' {
  declare module.exports: any;
}

// Filename aliases
declare module 'form-data/lib/browser.js' {
  declare module.exports: $Exports<'form-data/lib/browser'>;
}
declare module 'form-data/lib/form_data.js' {
  declare module.exports: $Exports<'form-data/lib/form_data'>;
}
declare module 'form-data/lib/populate.js' {
  declare module.exports: $Exports<'form-data/lib/populate'>;
}
